openapi: 3.2.0
info:
  title: Armory Scale Agent Applications & Clusters Server Group Manager Controller API
  description: Read operations across applications, clusters, server groups, server group managers, instances, load balancers, functions, raw resources and jobs.
  version: 0.13.x
  contact:
    name: Armory Docs
    url: https://docs.armory.io/plugins/scale-agent/
  x-origin:
  - format: swagger
    version: '2.0'
    url: https://docs.armory.io/reference/scale-agent/swagger.json
servers:
- url: /
tags:
- name: server-group-manager-controller
paths:
  /applications/{application}/serverGroupManagers:
    get:
      tags:
      - server-group-manager-controller
      summary: getForApplication
      operationId: getForApplicationUsingGET
      parameters:
      - name: application
        in: path
        description: application
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerGroupManager'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    ServerGroupManager:
      type: object
      properties:
        account:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
        moniker:
          $ref: '#/components/schemas/Moniker'
        name:
          type: string
        region:
          type: string
        serverGroups:
          type: array
          items:
            $ref: '#/components/schemas/ServerGroupSummary'
      title: ServerGroupManager
    Moniker:
      type: object
      properties:
        app:
          type: string
        cluster:
          type: string
        detail:
          type: string
        sequence:
          type: integer
          format: int32
        stack:
          type: string
      title: Moniker
    ServerGroupSummary:
      type: object
      properties:
        account:
          type: string
        moniker:
          $ref: '#/components/schemas/Moniker'
        name:
          type: string
        region:
          type: string
      title: ServerGroupSummary
