openapi: 3.2.0
info:
  title: Armory Scale Agent Infrastructure Instance Type Controller API
  description: Cloud infrastructure lookups - networks, subnets, VPCs, security groups, elastic IPs, instance types, reservation reports and search.
  version: 0.13.x
  contact:
    name: Armory Docs
    url: https://docs.armory.io/plugins/scale-agent/
  x-origin:
  - format: swagger
    version: '2.0'
    url: https://docs.armory.io/reference/scale-agent/swagger.json
servers:
- url: /
tags:
- name: instance-type-controller
paths:
  /instanceTypes:
    get:
      tags:
      - instance-type-controller
      summary: list
      operationId: listUsingGET_3
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstanceType'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    InstanceType:
      type: object
      properties:
        name:
          type: string
      title: InstanceType
