openapi: 3.2.0
info:
  description: Cloud read and write operations
  title: clouddriver Agent Accounts Controller API
  contact:
    name: admin@host.net
servers:
- url: https://localhost:7002/
tags:
- name: agent-accounts-controller
paths:
  /agents/kubernetes/accounts/{accountName}:
    get:
      tags:
      - agent-accounts-controller
      summary: Retrieve account by name if handled by armory agent
      operationId: getAccountUsingGET
      parameters:
      - name: accountName
        in: path
        description: accountName
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/KubesvcAccount'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /agents/kubernetes/accounts/{accountName}/namespaces:
    get:
      tags:
      - agent-accounts-controller
      summary: Retrieve namespaces by account name if handled by armory agent
      operationId: getNamespacesUsingGET
      parameters:
      - name: accountName
        in: path
        description: accountName
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    KubesvcAccount:
      type: object
      required:
      - definition
      - definitionAsString
      - name
      - permissions
      - properties
      - propertiesAsString
      properties:
        certFingerprint:
          type: string
        def:
          type: string
        definition:
          type: object
        definitionAsString:
          type: string
        dynamic:
          type: boolean
        errorMessage:
          type: string
        kubeHost:
          type: string
        kubeVersion:
          type: string
        lastUpdated:
          type: integer
          format: int64
        maxWatchAgeSeconds:
          type: integer
          format: int64
        name:
          type: string
        permissions:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        properties:
          type: object
        propertiesAsString:
          type: string
        props:
          type: string
        status:
          type: string
          enum:
          - ACTIVATING
          - ACTIVE
          - DEACTIVATING
          - FAILED
          - INACTIVE
          - TO_DEACTIVATE
          - TO_MIGRATE
          - ORPHANED
        zoneId:
          type: string
      title: KubesvcAccount
