openapi: 3.2.0
info:
  description: Cloud read and write operations
  title: clouddriver Raw Resource Controller API
  contact:
    name: admin@host.net
servers:
- url: https://localhost:7002/
tags:
- name: raw-resource-controller
paths:
  /applications/{application}/rawResources:
    get:
      tags:
      - raw-resource-controller
      summary: list
      operationId: listUsingGET_7
      parameters:
      - name: application
        in: path
        description: application
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KubernetesRawResource'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    KubernetesApiVersion:
      type: object
      properties:
        apiGroup:
          $ref: '#/components/schemas/KubernetesApiGroup'
      title: KubernetesApiVersion
    Moniker:
      type: object
      properties:
        app:
          type: string
        cluster:
          type: string
        detail:
          type: string
        sequence:
          type: integer
          format: int32
        stack:
          type: string
      title: Moniker
    KubernetesKind:
      type: object
      properties:
        apiGroup:
          $ref: '#/components/schemas/KubernetesApiGroup'
      title: KubernetesKind
    KubernetesRawResource:
      type: object
      properties:
        account:
          type: string
        apiVersion:
          $ref: '#/components/schemas/KubernetesApiVersion'
        createdTime:
          type: integer
          format: int64
        displayName:
          type: string
        kind:
          $ref: '#/components/schemas/KubernetesKind'
        labels:
          type: object
          additionalProperties:
            type: string
        moniker:
          $ref: '#/components/schemas/Moniker'
        name:
          type: string
        namespace:
          type: string
        region:
          type: string
      title: KubernetesRawResource
    KubernetesApiGroup:
      type: object
      properties:
        nativeGroup:
          type: boolean
      title: KubernetesApiGroup
